version: '3.8'

services:
  camerexpress-pricing-api:
    build: .
    container_name: camerexpress-pricing-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx512m -Xms256m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/pricing/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - camerexpress-network

  nginx:
    image: nginx:alpine
    container_name: camerexpress-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - camerexpress-pricing-api
    networks:
      - camerexpress-network



networks:
  camerexpress-network:
    driver: bridge